force-app/main/default/objects/CodeysRestaurantMenus__c/CodeysRestaurantMenus__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Codey&apos;s Restaurant Menus Custom Setting - Menu A, Menu B</description>
    <label>Codey&apos;s Restaurant Menus</label>
</CustomObject>

force-app/main/default/objects/Product2/fields/Rich_Image__c.field-meta.xml
<CustomField>
    <fullName>Rich_Image__c</fullName>
    <label>Rich Image</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/RestaurantController.cls
/**
 * Created by Harmath Zsolt on 2025. 03. 17..
 */

public with sharing class RestaurantController {
	@AuraEnabled
	public static CodeysRestaurantMenus__c getCodeysRestaurantMenus() {
		return CodeysRestaurantMenus__c.getInstance();
	}

	@AuraEnabled
	public static Map<Id, Product2> getAllFoods() {
		return new Map<Id, Product2>([
			SELECT Id
				,Name
				,Family
				,Rich_Image__c

				,(SELECT Id
					,Pricebook2Id
					,Pricebook2.Name
					,UnitPrice
				FROM PricebookEntries)

			FROM Product2
			WHERE Family = 'Food'
		]);
	}

	@AuraEnabled
	public static Order takeOrderFromBasket(String basketJson) {
		Order order = new Order();
		// TODO - fill order data from basketJson
		insert order;
		return order;
	}
}